### ISSUE TITLE
The `check_git_tag` step of the release pipeline doesn't work as expected

### ISSUE THREAD

**Issue by bfs-rca** [SpiGes/handbook#183]
In the following definition, a tag name without `v` prefix is expected, whereas the release creation step add this prefix. So an existing tag is never found:

```
check_git_tag:
    needs: [extract_release_version]
    runs-on: ubuntu-latest
    if: always() && success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if tag exists
        if: success()
        env:
          RELEASE_VERSION: ${{ needs.extract_release_version.outputs.release_version }}
        run: |
          if git rev-parse "refs/tags/$RELEASE_VERSION" >/dev/null 2>&1; then
            echo "Tag $RELEASE_VERSION already exists."
            exit 1
          else
            echo "Tag $RELEASE_VERSION does not exist."
          fi
```

Create release step:
```
create-release:
    needs: [deploy, extract_release_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: always() && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        env:
          RELEASE_VERSION: ${{ needs.extract_release_version.outputs.release_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "release version = $RELEASE_VERSION"
          gh release create "v$RELEASE_VERSION" --title "Release $RELEASE_VERSION" --notes-file RELEASE_NOTES.md --draft
```
